# Generated by Django 5.1.4 on 2025-01-14 02:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Food type must contain only letters and spaces.', regex='^[a-zA-Z\\s]*$')])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Description contains invalid characters.', regex='^[a-zA-Z0-9\\s,.-]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact number must be a valid phone number (e.g., +1234567890).', regex='^\\+?[1-9]\\d{1,14}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Description contains invalid characters.', regex='^[a-zA-Z0-9\\s,.-]*$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Recipe name must contain only letters, numbers, and spaces.', regex='^[a-zA-Z0-9\\s]*$')])),
                ('recipe', models.TextField(validators=[django.core.validators.RegexValidator(message='Recipe details contain invalid characters.', regex='^[a-zA-Z0-9\\s,.-]*$')])),
                ('duration', models.TextField(validators=[django.core.validators.RegexValidator(message='Duration must be a number, optionally followed by units (e.g., "30 minutes").', regex='^[0-9]+(\\s*[a-zA-Z]*)?$')])),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Requested role must contain only letters and spaces.', regex='^[a-zA-Z\\s]*$')])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
