# Generated by Django 5.1.4 on 2025-01-19 06:11

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webapp', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipes',
            name='author_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='auth.group'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 0, 0)),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default='No description provided', validators=[django.core.validators.RegexValidator(message='Recipe description contains invalid characters.', regex='^[a-zA-Z0-9\\s,.-]*$')]),
        ),
        migrations.AddField(
            model_name='recipes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='duration',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Duration must be a number, optionally followed by units (e.g., "30 minutes").', regex='^[0-9]+(\\s*[a-zA-Z]*)?$')]),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='food_type',
            field=models.ForeignKey(help_text='Select the type of food this recipe belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='webapp.foodtype'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Recipe name must contain only letters, numbers, and spaces.', regex='^[a-zA-Z0-9\\s]*$')]),
        ),
    ]
