# Generated by Django 5.1.4 on 2025-02-01 15:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_method_delete_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Enter cooking duration in minutes.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='recipes',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.method'),
        ),
    ]
