# Generated by Django 5.1.4 on 2025-02-08 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_recipes_duration_recipes_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
